name: 📰 Publish to Netlify

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup pnpm environment
        uses: ./.github/actions/setup-pnpm

      - name: Build
        run: |
          pnpm build

      - name: Deploy
        uses: nwtgck/actions-netlify@v3.0.0
        with:
          publish-dir: './build'
          production-branch: main
          github-token: ${{ secrets.GH_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          HUSKY: 0
